# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  # aliased to a recent 5.4.x version
  - 5.4
  # aliased to a recent 5.5.x version
  - 5.5
  # aliased to a recent 5.6.x version
  - 5.6

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - curl -sS https://getcomposer.org/installer | php

install:
  - php composer.phar install

# omitting "script:" will default to phpunit
script: vendor/bin/phpunit -c tests/

# configure notifications (email, IRC, campfire etc)
notifications:
  email:
    recipients:
      - irgalieri@gmail.com
    on_success: change
    on_failure: always
