sudo: false
language: "php"

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
- "composer require codeclimate/php-test-reporter --dev"
- "composer install"

script:
- "vendor/bin/phpunit -c tests/phpunit.xml --coverage-clover build/logs/clover.xml"

after_script:
- CODECLIMATE_REPO_TOKEN="80fe14a5be018f61a1f987432c6d0f038dec5968d2aab740fdbdb2274437699e" vendor/bin/test-reporter --stdout > codeclimate.json
- "sh -c 'if [ \"$TRAVIS_PHP_VERSION\" != \"hhvm\" ]; then curl -X POST -d @codeclimate.json -H \"Content-Type: application/json\" -H \"User-Agent: Code Climate (PHP Test Reporter v0.1.1)\" https://codeclimate.com/test_reports  ; fi'"
